### ISSUE TITLE
Ahom i–u ligature is still not always formed

### ISSUE THREAD

**Issue by dscorbett** [notofonts/ahom#16]
### Font
NotoSerifAhom-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/ahom/releases/tag/NotoSerifAhom-v2.006
Date: 2023-03-24

### Font version
Version 2.006

### Issue
Issue #12 still exists for syllables where the base letter and the ⟨<i>-i</i>, <i>-u</i>⟩ sequence are separated by U+1171E AHOM CONSONANT SIGN MEDIAL RA or by multiple code points.

Rather than extending the fix implemented for that issue, I recommend a two-part solution. First, do the ligation after reordering instead of in 'ccmp', so that you don’t have to handle U+11726 AHOM VOWEL SIGN E explicitly. Second, use a mark set in the ligature lookup, so that irrelevant marks like U+1171D are skipped.

### Character data
𑜀𑜞𑜢𑜤
U+11700 AHOM LETTER KA
U+1171E AHOM CONSONANT SIGN MEDIAL RA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

𑜀
U+11700 AHOM LETTER KA
U+1171D AHOM CONSONANT SIGN MEDIAL LA
U+11726 AHOM VOWEL SIGN E
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

### Screenshot
![𑜀𑜞𑜢𑜤](https://user-images.githubusercontent.com/1124347/227621159-fc720a6b-6371-4ea3-b133-7060ef657443.png)
![𑜀](https://user-images.githubusercontent.com/1124347/227621381-dfc9a03e-fdd7-44c5-a3eb-cae7bb84d15a.png)

**Comment by StephenMorey** [comment]
Thank you for the comment on this dscorbett. I am sorry that I didn't see this earlier, I need to get better at following Github. 

There are two issues with the examples that you have given. (1) with this consonant, and most others, the combination of AHOM VOWEL SIGN I (U+11722) and AHOM VOWEL SIGN U (U+11724) should convert to the contextual ligature after all consonants except NA, NYA, DA and NGA. Even with the use of U+1171E AHOM CONSONANT SIGN MEDIAL RA, the contextual ligature should appear as we see when we type
𑜀𑜢𑜤
U+11700 AHOM LETTER KA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

(2) Secondly, with the four initial consonants NA, NYA, DA and NGA, the contextual ligature is not used, but the combination of AHOM VOWEL SIGN I (U+11722) and AHOM VOWEL SIGN U (U+11724) should appear so that middle of the AHOM VOWEL SIGN I vowel is directly above the vertical portion of the AHOM VOWEL SIGN U, whereas at present, the VOWEL SIGN I is too far to the right of the middle of the vowel sign U.

Consider
𑜃𑜢𑜤
U+11703 AHOM LETTER NA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

**Comment by StephenMorey** [comment]
Thank you for re-opening Simon. Let me know if enough information has been provided.

**Comment by simoncozens** [comment]
Yes! I'll take a look at this and fix... at some point. (Sorry I can't be more specific.)

**Comment by StephenMorey** [comment]
Thank you.

**Comment by simoncozens** [comment]
Now we have:

![shape](https://github.com/notofonts/ahom/assets/106728/bdbac443-00de-4ca5-8bcc-d4e2035768dc)

**Comment by StephenMorey** [comment]
Simon,
That looks really nice (my apologies for late response)
Can you let me know where I can find the updated font on here or on the Noto site? I'm sorry but when I recently downloaded a package and installed the package NotoSerifAhom-v2.007_20230927, and then installed the font NotoSerifAhom-Regular.ttf from the full .ttf folder, it didn't look like this.
