### ISSUE TITLE
Need for doubled combination of 01172A and 01172B

### ISSUE THREAD

**Issue by StephenMorey** [notofonts/ahom#22]
### Title 
Need for doubled combination of 01172A and 01172B

### Font 
NOTOSERIFAHOM-REGULAR.ttf

### Font Version
Version 2.006 ttfautohint (v 1.8.4.7-5d5b)

### Issue
In some Tai Ahom manuscripts, the combination of 01172A (Ahom Vowel Sign AM) and 01172B (Ahom SIgn Virama) are repeated to indicated a reduplicated subject. This example from a Tai Ahom manuscript known as Ma Likha Lit shows this doubling in combinations with a single 0112C8 (AHOM LETTER MA) and 0112E8 (AHOM VOWEL SIGN O)
![image](https://github.com/user-attachments/assets/8146d50b-abc5-4d5f-ac5b-437e78a25d23)

At present the best way to realise this is to put the characters in as 011709 01172A 011728 00A0 01172B 00A0 01172A 01172B, which appears as 
![image](https://github.com/user-attachments/assets/8a7cf537-a75b-43da-a6df-c101aa67261d)

**Comment by r12a** [comment]
I'm not sure we want people typing nbsp to get the right display.  If you reorder the codepoints so that all the above marks occur before the below marks, ie.

𑜉  U+11709 AHOM LETTER MA𑜪  
U+1172A AHOM VOWEL SIGN AM​𑜫  
U+1172B AHOM SIGN KILLER​𑜪  
U+1172A AHOM VOWEL SIGN AM​𑜫  
U+1172B AHOM SIGN KILLER​𑜨  
U+11728 AHOM VOWEL SIGN O​

you get this:

<img width="112" alt="Screenshot 2024-11-24 at 16 19 28" src="https://github.com/user-attachments/assets/35387b91-1b10-441b-bab3-ff2ee7874f66">

which is close to what you want, except that the killer signs needs to be lifted above the vowel signs. (I think the relative positioning of adjacent marks in the same location relative to the base needs a bit of attention for other combinations too.)

**Comment by StephenMorey** [comment]
Thank you, yes the image is close to what we want, except that the killer needs to be lifted.
Because 1172B is a ʹkillerʹ and always written last in handwriting, it is a little strange to users of the script to ype 1172A after 1172B, but I think that the keyboard can deal with that.
Is it possible to get the killer lifted after the U+1172A?

Note that this is an unsual and uncommon combination, but it does exist in manuscripts so it will be much appreciated if the font can be slightly adjusted. Thank you

**Comment by simoncozens** [comment]
The sequence now produces this:

![shape](https://github.com/user-attachments/assets/320bb0be-eed4-4d59-a039-79c65a94ea9d)
